<a href="https://colab.research.google.com/github/CamiloLezcanoUdea/ClasesPython20242/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#1. Crear un array de una dimensión
array1 = np.array([1, 2, 3, 4, 5, 6])
print(array1)

[1 2 3 4 5 6]


In [4]:
#2. Crear un array de 2 dimensiones
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array2)

[[1 2 3]
 [4 5 6]]


In [6]:
#3. Crear un array de ceros
zeros = np.zeros((5, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#4. crear array de unos
ones = np.ones((3, 6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
#5. crear un array vacio
empty_array = np.empty((2, 3))
print(empty_array)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [10]:
#6. crear un array con u nrango de numeros
range_array = np.arange(11)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [13]:
#7. crear array con un rango y un paso
range_step_array = np.arange(1, 10, 3)
print(range_step_array)

[1 4 7]


In [15]:
#8. crear un array de valores aleatorios
random_array = np.random.rand(4, 3)
print(random_array)

[[0.19855977 0.2348883  0.1854794 ]
 [0.16523565 0.44320868 0.43018757]
 [0.71233964 0.57457201 0.69674474]
 [0.41977336 0.75562428 0.80238006]]


In [16]:
#9. crear un array de valores aleatorios enteros
random_int_array = np.random.randint(0, 10, (3, 3))
print(random_int_array)

[[1 9 6]
 [6 2 3]
 [9 9 0]]


In [18]:
#10. crear un array de numeros en intervalos
linespace_array = np.linspace(0, 1, 5)
print(linespace_array)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
#11. cambiar la forma de un array
reshaped_array = np.reshape(array2, (3, 2))
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
#12. como dterminar la forma de un array
print(reshaped_array.shape)

(3, 2)


In [23]:
#13. numero dimensiones de un array
print(reshaped_array.ndim)

2


In [24]:
#14. tamaño de un array
print(array2.size)

6


In [25]:
#15. tipos de datos del array
print(array2.dtype)

int64


In [28]:
#16. convertir el tipo de datos de un array
float_array = array2.astype(object)
print(float_array)

[[1 2 3]
 [4 5 6]]


In [29]:
#17. sumar todos los elementos de un array
sum_all = np.sum(array2)
print(sum_all)

21


In [30]:
#18. sumar los elementos a lo largo de una dimension
sum_axis_0 = np.sum(array2, axis=0)
print(sum_axis_0)

[5 7 9]


In [31]:
#19. calcular el promedio array
mean_value = np.mean(array2)
print(mean_value)

3.5


In [32]:
#20. calcular la mediana de un array
median_value = np.median(array2)
print(median_value)

3.5


In [33]:
#21. calcular el valores minimo y maximo
max_array = np.max(array2)
min_array = np.min(array2)
print(min_array, max_array)

1 6


In [34]:
#22. calcular la desviacion estandar
std_dev = np.std(array2)
print(std_dev)

1.707825127659933


In [36]:
#23. encontrar el indice del valor maximo
max_index = np.argmax(array2)
print(max_index)

5


In [37]:
#24. encontrar el indice del valor minimo
min_index = np.argmin(array2)
print(min_index)

0


In [44]:
#25. indexacion de un array
print(array1[5])

6


In [47]:
#26. indexacion de un array de 2D
print(array2)
print(array2[0, 1])

[[1 2 3]
 [4 5 6]]
2


In [49]:
#27. Slicing de un array
scliced_array = array1[1:5]
print(scliced_array)

[2 3 4 5]


In [51]:
#28. invertir un array
reversed_array = array1[::-1]
print(reversed_array)

[6 5 4 3 2 1]


In [53]:
#29. indexacion booleana
filtered_array = array1[array1 < 3]
print(filtered_array)

[1 2]


In [59]:
#30. sumar arrays
added_arrays = array1 + np.array([5, 5, 5, 5, 5, 5])
print(added_arrays)

[ 6  7  8  9 10 11]


In [61]:
#31. restar arrays
subtracted_arrays = array1 - np.array([1, 1, 1, 1, 1, 1])
print(subtracted_arrays)

[0 1 2 3 4 5]


In [62]:
#32. multiplicar arrays
multiplied_arrays = array1 * np.array([2, 2, 2, 2, 2, 2])
print(multiplied_arrays)

[ 2  4  6  8 10 12]


In [63]:
#33. division de arrays
divided_arrays = array1 / 2
print(divided_arrays)

[0.5 1.  1.5 2.  2.5 3. ]


In [71]:
#34. calcular el producto de matrices
matrix_product = np.dot(array2, np.array([[1,2], [3,4], [5,6]]))
print(array2)
print("***************")
print(np.array([[1,2], [3,4], [5,6]]))
print("***************")
print("[0,0] = [1*1 + 2*3 + 3*5] = 22")
print("[0,1] = [1*2 + 2*4 + 3*6] = 28")
print("[1,0] = [4*1 + 5*3 + 6*5] = 49")
print("[1,1] = [4*2 + 5*4 + 6*6] = 64")
print("***************")
print(matrix_product)

[[1 2 3]
 [4 5 6]]
***************
[[1 2]
 [3 4]
 [5 6]]
***************
[0,0] = [1*1 + 2*3 + 3*5] = 22
[0,1] = [1*2 + 2*4 + 3*6] = 28
[1,0] = [4*1 + 5*3 + 6*5] = 49
[1,1] = [4*2 + 5*4 + 6*6] = 64
***************
[[22 28]
 [49 64]]


In [67]:
#35. transponer un array(pivot pandas)
transposed_array = np.transpose(array2)
print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


In [68]:
#36. obtener la diagonal de un array
diagonal = np.diag(array2)
print(diagonal)

[1 5]


In [72]:
#37. Redondear cada elemento
rounded_array = np.round(random_array)
print(rounded_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [0. 1. 1.]]
